FROM ros:melodic
RUN sudo apt update
RUN sudo apt install -y software-properties-common
RUN sudo apt-get install -y python3
RUN sudo apt install -y python3.8
RUN sudo apt-get install -y python3.8-dev
RUN sudo apt update && sudo apt-get install -y python3-pip wget unzip
RUN export CLOUDSDK_PYTHON=python3.8
